/*
 * This file is generated by jOOQ.
 */
package com.wqh.hummingbird.server.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UShort;


/**
 * 数据点位信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataPoint implements Serializable {

    private static final long serialVersionUID = 1697015124;

    private Long   id;
    private UShort deviceTypeId;
    private UShort dataPoint;
    private UShort ability;
    private UShort dataType;
    private String name;
    private String description;

    public DataPoint() {}

    public DataPoint(DataPoint value) {
        this.id = value.id;
        this.deviceTypeId = value.deviceTypeId;
        this.dataPoint = value.dataPoint;
        this.ability = value.ability;
        this.dataType = value.dataType;
        this.name = value.name;
        this.description = value.description;
    }

    public DataPoint(
        Long   id,
        UShort deviceTypeId,
        UShort dataPoint,
        UShort ability,
        UShort dataType,
        String name,
        String description
    ) {
        this.id = id;
        this.deviceTypeId = deviceTypeId;
        this.dataPoint = dataPoint;
        this.ability = ability;
        this.dataType = dataType;
        this.name = name;
        this.description = description;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UShort getDeviceTypeId() {
        return this.deviceTypeId;
    }

    public void setDeviceTypeId(UShort deviceTypeId) {
        this.deviceTypeId = deviceTypeId;
    }

    public UShort getDataPoint() {
        return this.dataPoint;
    }

    public void setDataPoint(UShort dataPoint) {
        this.dataPoint = dataPoint;
    }

    public UShort getAbility() {
        return this.ability;
    }

    public void setAbility(UShort ability) {
        this.ability = ability;
    }

    public UShort getDataType() {
        return this.dataType;
    }

    public void setDataType(UShort dataType) {
        this.dataType = dataType;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DataPoint (");

        sb.append(id);
        sb.append(", ").append(deviceTypeId);
        sb.append(", ").append(dataPoint);
        sb.append(", ").append(ability);
        sb.append(", ").append(dataType);
        sb.append(", ").append(name);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
