/*
 * This file is generated by jOOQ.
 */
package com.wqh.hummingbird.server.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UShort;


/**
 * 设备类型表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceType implements Serializable {

    private static final long serialVersionUID = 1861133848;

    private UShort id;
    private String name;
    private String description;

    public DeviceType() {}

    public DeviceType(DeviceType value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
    }

    public DeviceType(
        UShort id,
        String name,
        String description
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
    }

    public UShort getId() {
        return this.id;
    }

    public void setId(UShort id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DeviceType (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
