/*
 * This file is generated by jOOQ.
 */
package com.wqh.hummingbird.server.generator;


import com.wqh.hummingbird.server.generator.tables.DataPoint;
import com.wqh.hummingbird.server.generator.tables.Device;
import com.wqh.hummingbird.server.generator.tables.DeviceType;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>hummingbird_db</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DATA_POINT_DATA_POINT_DEVICE_TYPE_ID_NAME_INDEX = Indexes0.DATA_POINT_DATA_POINT_DEVICE_TYPE_ID_NAME_INDEX;
    public static final Index DATA_POINT_DATA_POINT_DEVICE_TYPE_ID_POINT_UINDEX = Indexes0.DATA_POINT_DATA_POINT_DEVICE_TYPE_ID_POINT_UINDEX;
    public static final Index DATA_POINT_PRIMARY = Indexes0.DATA_POINT_PRIMARY;
    public static final Index DEVICE_DEVICE_CODE_UINDEX = Indexes0.DEVICE_DEVICE_CODE_UINDEX;
    public static final Index DEVICE_DEVICE_NAME_UINDEX = Indexes0.DEVICE_DEVICE_NAME_UINDEX;
    public static final Index DEVICE_PRIMARY = Indexes0.DEVICE_PRIMARY;
    public static final Index DEVICE_TYPE_DEVICE_TYPE_NAME_UINDEX = Indexes0.DEVICE_TYPE_DEVICE_TYPE_NAME_UINDEX;
    public static final Index DEVICE_TYPE_PRIMARY = Indexes0.DEVICE_TYPE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DATA_POINT_DATA_POINT_DEVICE_TYPE_ID_NAME_INDEX = Internal.createIndex("data_point_device_type_id_name_index", DataPoint.DATA_POINT, new OrderField[] { DataPoint.DATA_POINT.DEVICE_TYPE_ID, DataPoint.DATA_POINT.NAME }, false);
        public static Index DATA_POINT_DATA_POINT_DEVICE_TYPE_ID_POINT_UINDEX = Internal.createIndex("data_point_device_type_id_point_uindex", DataPoint.DATA_POINT, new OrderField[] { DataPoint.DATA_POINT.DEVICE_TYPE_ID, DataPoint.DATA_POINT.DATA_POINT_ }, true);
        public static Index DATA_POINT_PRIMARY = Internal.createIndex("PRIMARY", DataPoint.DATA_POINT, new OrderField[] { DataPoint.DATA_POINT.ID }, true);
        public static Index DEVICE_DEVICE_CODE_UINDEX = Internal.createIndex("device_code_uindex", Device.DEVICE, new OrderField[] { Device.DEVICE.CODE }, true);
        public static Index DEVICE_DEVICE_NAME_UINDEX = Internal.createIndex("device_name_uindex", Device.DEVICE, new OrderField[] { Device.DEVICE.NAME }, true);
        public static Index DEVICE_PRIMARY = Internal.createIndex("PRIMARY", Device.DEVICE, new OrderField[] { Device.DEVICE.ID }, true);
        public static Index DEVICE_TYPE_DEVICE_TYPE_NAME_UINDEX = Internal.createIndex("device_type_name_uindex", DeviceType.DEVICE_TYPE, new OrderField[] { DeviceType.DEVICE_TYPE.NAME }, true);
        public static Index DEVICE_TYPE_PRIMARY = Internal.createIndex("PRIMARY", DeviceType.DEVICE_TYPE, new OrderField[] { DeviceType.DEVICE_TYPE.ID }, true);
    }
}
