/*
 * This file is generated by jOOQ.
 */
package com.wqh.hummingbird.server.generator;


import com.wqh.hummingbird.server.generator.tables.DataPoint;
import com.wqh.hummingbird.server.generator.tables.Device;
import com.wqh.hummingbird.server.generator.tables.DeviceType;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in hummingbird_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 数据点位信息
     */
    public static final DataPoint DATA_POINT = com.wqh.hummingbird.server.generator.tables.DataPoint.DATA_POINT;

    /**
     * 设备表
     */
    public static final Device DEVICE = com.wqh.hummingbird.server.generator.tables.Device.DEVICE;

    /**
     * 设备类型表
     */
    public static final DeviceType DEVICE_TYPE = com.wqh.hummingbird.server.generator.tables.DeviceType.DEVICE_TYPE;
}
