/*
 * This file is generated by jOOQ.
 */
package com.wqh.hummingbird.server.generator.tables.records;


import com.wqh.hummingbird.server.generator.tables.DataPoint;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;


/**
 * 数据点位信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataPointRecord extends UpdatableRecordImpl<DataPointRecord> implements Record7<Long, UShort, UShort, UShort, UShort, String, String> {

    private static final long serialVersionUID = 745513283;

    /**
     * Setter for <code>hummingbird_db.data_point.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hummingbird_db.data_point.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hummingbird_db.data_point.device_type_id</code>. 设备类型ID
     */
    public void setDeviceTypeId(UShort value) {
        set(1, value);
    }

    /**
     * Getter for <code>hummingbird_db.data_point.device_type_id</code>. 设备类型ID
     */
    public UShort getDeviceTypeId() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>hummingbird_db.data_point.data_point</code>.
     */
    public void setDataPoint(UShort value) {
        set(2, value);
    }

    /**
     * Getter for <code>hummingbird_db.data_point.data_point</code>.
     */
    public UShort getDataPoint() {
        return (UShort) get(2);
    }

    /**
     * Setter for <code>hummingbird_db.data_point.ability</code>. 0:R,1:W,2:RW
     */
    public void setAbility(UShort value) {
        set(3, value);
    }

    /**
     * Getter for <code>hummingbird_db.data_point.ability</code>. 0:R,1:W,2:RW
     */
    public UShort getAbility() {
        return (UShort) get(3);
    }

    /**
     * Setter for <code>hummingbird_db.data_point.data_type</code>. 数据类型
     */
    public void setDataType(UShort value) {
        set(4, value);
    }

    /**
     * Getter for <code>hummingbird_db.data_point.data_type</code>. 数据类型
     */
    public UShort getDataType() {
        return (UShort) get(4);
    }

    /**
     * Setter for <code>hummingbird_db.data_point.name</code>. 字段名称
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>hummingbird_db.data_point.name</code>. 字段名称
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>hummingbird_db.data_point.description</code>. 描述
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>hummingbird_db.data_point.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, UShort, UShort, UShort, UShort, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, UShort, UShort, UShort, UShort, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DataPoint.DATA_POINT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field2() {
        return DataPoint.DATA_POINT.DEVICE_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field3() {
        return DataPoint.DATA_POINT.DATA_POINT_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field4() {
        return DataPoint.DATA_POINT.ABILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field5() {
        return DataPoint.DATA_POINT.DATA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DataPoint.DATA_POINT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DataPoint.DATA_POINT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component2() {
        return getDeviceTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component3() {
        return getDataPoint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component4() {
        return getAbility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component5() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value2() {
        return getDeviceTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value3() {
        return getDataPoint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value4() {
        return getAbility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value5() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataPointRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataPointRecord value2(UShort value) {
        setDeviceTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataPointRecord value3(UShort value) {
        setDataPoint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataPointRecord value4(UShort value) {
        setAbility(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataPointRecord value5(UShort value) {
        setDataType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataPointRecord value6(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataPointRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataPointRecord values(Long value1, UShort value2, UShort value3, UShort value4, UShort value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataPointRecord
     */
    public DataPointRecord() {
        super(DataPoint.DATA_POINT);
    }

    /**
     * Create a detached, initialised DataPointRecord
     */
    public DataPointRecord(Long id, UShort deviceTypeId, UShort dataPoint, UShort ability, UShort dataType, String name, String description) {
        super(DataPoint.DATA_POINT);

        set(0, id);
        set(1, deviceTypeId);
        set(2, dataPoint);
        set(3, ability);
        set(4, dataType);
        set(5, name);
        set(6, description);
    }
}
