/*
 * This file is generated by jOOQ.
 */
package com.wqh.hummingbird.server.generator.tables.records;


import com.wqh.hummingbird.server.generator.tables.Device;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;


/**
 * 设备表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceRecord extends UpdatableRecordImpl<DeviceRecord> implements Record5<Long, UShort, String, String, Boolean> {

    private static final long serialVersionUID = 576247217;

    /**
     * Setter for <code>hummingbird_db.device.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hummingbird_db.device.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hummingbird_db.device.type_id</code>. 设备类型
     */
    public void setTypeId(UShort value) {
        set(1, value);
    }

    /**
     * Getter for <code>hummingbird_db.device.type_id</code>. 设备类型
     */
    public UShort getTypeId() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>hummingbird_db.device.code</code>. 设备编码
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hummingbird_db.device.code</code>. 设备编码
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hummingbird_db.device.name</code>. 设备名称
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>hummingbird_db.device.name</code>. 设备名称
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>hummingbird_db.device.online</code>. 是否在线
     */
    public void setOnline(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>hummingbird_db.device.online</code>. 是否在线
     */
    public Boolean getOnline() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, UShort, String, String, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, UShort, String, String, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Device.DEVICE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field2() {
        return Device.DEVICE.TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Device.DEVICE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Device.DEVICE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Device.DEVICE.ONLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component2() {
        return getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getOnline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value2() {
        return getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getOnline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value2(UShort value) {
        setTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value3(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord value5(Boolean value) {
        setOnline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeviceRecord values(Long value1, UShort value2, String value3, String value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeviceRecord
     */
    public DeviceRecord() {
        super(Device.DEVICE);
    }

    /**
     * Create a detached, initialised DeviceRecord
     */
    public DeviceRecord(Long id, UShort typeId, String code, String name, Boolean online) {
        super(Device.DEVICE);

        set(0, id);
        set(1, typeId);
        set(2, code);
        set(3, name);
        set(4, online);
    }
}
